Exam/urls.py
from django.contrib import admin
from django.urls import path,include
from Exam import views
urlpatterns = [
    path('',views.index,name="index"),
    # path('about',views.about,name="about"),
    # path('purpose',views.purpose,name="purpose"),
    # path('contact',views.contact,name="contact"),
    
    

]

ONLINE_EXAM/urls.py
from django.contrib import admin
from django.urls import path,include
from Student import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('Exam.urls')),
    path('admin/', include('admin.urls')),
    path('student/',include('Student.urls')),
        
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Student/urls.py
from django.urls import path
from Student import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "student"

urlpatterns = [
    path('',views.index,name="index"),
    path('signup',views.signup,name="signup"),
    path('about',views.about,name="about"),
    path('purpose',views.purpose,name="purpose"),
    path('contact',views.contact,name="contact"),    
    path('signin',views.signin,name="signin"),
    path('studentdeshboard',views.studentdeshboard,name="studentdeshboard"),
    path('stud_feedback/',views.feedback,name="stud_feedback"),
    path('student_exam/',views.student_exam,name="student_exam"),
    path('take_exam/<id>',views.take_exam,name="take_exam"),
    path('start_exam/<id>',views.start_exam,name="start_exam"),
    path('student_marks/',views.student_marks,name="student_marks"),
    path('view_result', views.view_result_view,name='view_result'),
    path('check_marks/<int:pk>',views.check_marks,name='check_marks'),
    path('stud_logout/',views.stud_logout,name="stud_logout"),
    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Student/models.py
from django.db import models
# Create your models here.
class Signup(models.Model):
    firstname=models.CharField(max_length=20)
    lastname=models.CharField(max_length=20)
    contact=models.CharField(max_length=12)
    email=models.CharField(max_length=20)
    password=models.CharField(max_length=8)  
    city=models.CharField(max_length=40)
    profile_photo=models.ImageField(upload_to='profile_pic')
    
    def __str__(self):
        return self.email
    

Student/views.py
from django.shortcuts import render,redirect
from Student.models import *
from admin.models import *
from django.contrib import messages
import datetime
from django.contrib.auth import logout
# Create your views here.

def index(request):
    return render(request,'index.html')

def about(request):
    return render(request,'about.html')

def purpose(request):
     return render(request,'purpose.html')

def contact(request):   
   if request.method =='POST':
      name=request.POST.get('username')
      email_id=request.POST.get('email')
      contact_no=request.POST.get('phone')
      message=request.POST.get('message')
      contact = Contact (name=name,email_id=email_id,contact_no=contact_no,message=message)
      contact.save()
      messages.success(request, 'Your message is sent to admin we can contact you in 24 hours.')
   return render(request,'contact.html')

def signup(request):
    if request.method =='POST':
        firstname=request.POST.get('firstname') 
        lastname=request.POST.get('lastname')   
        contact=request.POST.get('contact') 
        email=request.POST.get('email')        
        password=request.POST.get('password')   
        city=request.POST.get('city')        
        profile_photo=request.FILES['profile_photo']    
        signup = Signup (firstname=firstname,lastname=lastname,contact=contact,email=email,password=password,city=city,profile_photo=profile_photo)
        signup.save()   
        messages.success(request, 'Regiter Successfully!')  
    return render(request,'student/signup.html')    

def signin(request):
    if request.method=='POST':  
        eml=request.POST['email']   
        pas=request.POST['password']    
        user_obj=Signup.objects.filter(email=eml,password=pas)  
        if user_obj:    
            print('Login successfully!')    
            user_data=Signup.objects.get(email=eml,password=pas)
            request.session['e_id']= user_data.id
            u_id = request.session.get('e_id')
            print("My_session_id :",u_id) 
            print('session pass')   
            return redirect('student:studentdeshboard') 
        else:   
            print('Login faild....something went wrong - Try again.')   
    return render(request, 'student/signin.html')   

def studentdeshboard(request):  
    e_id=request.session.get('e_id')   
    print('ddddd :',e_id) 
    print('get session... studentdeshboard page')   
    total_course=Course.objects.all().count()
    total_question=Question.objects.all().count()
    return render(request, 'student/studentdeshboard.html',{'e_id':e_id,'total_course':total_course,'total_question':total_question})


def student_exam(request):  
    e_id=request.session.get('e_id')    
    print('get session... studentdeshboard page')  
    t = Course.objects.all() 
    return render(request, 'student/student_exam.html',{'e_id':e_id,'courses':t})

def take_exam(request,id):
    course=Course.objects.get(id=id)
    total_questions=Question.objects.all().filter(course=course).count()
    questions=Question.objects.all().filter(course=course)
    total_marks=0
    for q in questions:
        total_marks=total_marks + q.marks    
    return render(request,'student/take_exam.html',{'course':course,'total_questions':total_questions,'total_marks':total_marks})

def start_exam(request,id):
    course=Course.objects.get(id=id)
    questions=Question.objects.all().filter(course=course)
    no_of_questions=Question.objects.all().filter(course=course).count()
    if request.method=='POST':
        total_marks=0
        for q in questions:
            print('Answer :',q.answer)
            for key in request.POST:
                print(key)
                value = request.POST[key]
                if value == q.answer:
                    total_marks = total_marks + q.marks
                    print("Badu_Marks: ",total_marks)
                print("First",value)
        result = Result()
        u_id = request.session.get('e_id')
        student = Signup.objects.get(id=u_id)
        result.marks=total_marks
        result.exam=course
        result.student=student
        result.date=datetime.datetime.now()
        result.save()
        return redirect('student:view_result')    
    response= render(request,'student/start_exam.html',{'course':course,'questions':questions})
    response.set_cookie('course_id',course.id)
    return response

# def calculate_marks(request):
#     if request.COOKIES.get('course_id') is not None:
#         course_id = request.COOKIES.get('course_id')
#         course=Course.objects.get(id=course_id)        
#         total_marks=0
#         questions=Question.objects.all().filter(course=course)
#         for i in range(len(questions)):            
#             selected_ans = request.COOKIES.get(str(i+1))
#             actual_answer = questions[i].answer
#             if selected_ans == actual_answer:
#                 total_marks = total_marks + questions[i].marks
#         u_id = request.session.get('e_id')
#         student = Signup.objects.get(id=u_id)
#         result = Result()
#         result.marks=total_marks
#         result.exam=course
#         result.student=student
#         result.save()
#         return redirect('student:view_result')

def view_result_view(request):
    courses=Course.objects.all()
    return render(request,'student/view_result.html',{'courses':courses})

def check_marks(request,pk):
    course=Course.objects.get(id=pk)
    u_id = request.session.get('e_id')
    print("student_iddddd:",u_id)
    student = Signup.objects.get(id=u_id)
    results=Result.objects.all().filter(exam=course).filter(student=student)
    return render(request,'student/check_marks.html',{'results':results})

def student_marks(request):
    courses=Course.objects.all()
    return render(request,'student/student_marks.html',{'courses':courses})

def feedback(request):  
    return render(request, 'student/stud_feedback.html')    

def stud_logout(request):  
    logout(request)
    try:
        del request.session['e_id'] 
    except Exception as e:
        print(e)
    return redirect('/')

templates/student/base_student.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
 

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    body {
      margin: 0;
      padding: 0;
      font-family: "Gill Sans", sans-serif;;
    }

    header {
      position: fixed;
      background: #22242A;
      padding: 20px;
      width: 100%;
      z-index: 1;
    }

    .left_area h3 {
      color: #fff;
      margin: 0px;
      text-transform: uppercase;
      font-size: 22px;
      font-weight: 900;
    }

    .left_area span {
      color: #19B3D3;
    }

    .logout_btn {
      padding: 5px;
      background: #19B3D3;
      text-decoration: none;
      float: right;
      margin-top: -30px;
      margin-right: 40px;
      border-radius: 2px;
      font-size: 15px;
      font-weight: 600;
      color: #fff;
      transition: 0.5s;

    }

    .logout_btn:hover {
      background: #0B87A6;
    }

    .sidebar {
      background: #2f323a;
      margin-top: 70px;
      padding-top: 30px;
      position: fixed;
      left: 0;
      width: 250px;
      height: 100%;
      transition: 0.5s;
      transition-property: left;
    }

    .sidebar .profile_image {
      width: 100px;
      height: 100px;
      border-radius: 100px;
      margin-bottom: 10px;
    }

    .sidebar h4 {
      color: #ccc;
      margin-top: 0;
      
    }

    .sidebar a {
      color: #fff;
      display: block;
      width: 100%;
      line-height: 60px;
      text-decoration: none;
      padding-left: 40px;
      box-sizing: border-box;
      transition: 0.5s;

    }

    .sidebar a:hover {
      background: #19B3D3;
    }

    .sidebar i {
      padding-right: 10px;
    }

    label #sidebar_btn {
      z-index: 1;
      color: #fff;
      position: fixed;
      cursor: pointer;
      left: 300px;
      font-size: 20px;
      margin: 5px 0;
      transition: 0.5s;
      transition-property: color;
    }

    label #sidebar_btn:hover {
      color: #19B3D3;
    }

    #check:checked~.sidebar {
      left: -190px;
    }

    #check:checked~.sidebar a span {
      display: none;
    }

    #check:checked~.sidebar a {
      font-size: 20px;
      margin-left: 170px;
      width: 80px;
    }

    .content {
      margin-left: 250px;
      background: url(background.png) no-repeat;
      background-position: center;
      background-size: cover;
      height: 100vh;
      transition: 0.5s;
    }

    #check:checked~.content {
      margin-left: 60px;
    }

    #check {
      display: none;
    }
  </style>


  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">


</head>

<body>

  <input type="checkbox" id="check">
  <!--header area start-->
  <header>
    <label for="check">
      <i style="left: 200px;margin-top: 17px;"class="fas fa-bars" id="sidebar_btn"></i>
    </label>
    <div class="left_area">
      <h3>eExam</h3>
    </div>
    <div class="right_area">
      <a href="{% url 'student:stud_logout' %}" class="logout_btn">Logout</a> 
      
    </div>
  </header>
  <!--header area end-->
  <!--sidebar start-->
  <div class="sidebar">
    <center>

      <img src="{% static "images/a2.jpg" %}" class="profile_image" alt="">
      <h4>{{request.signup.firstname}}</h4>
      <h6 style="color: rgb(255, 255, 255);">( Student )</h6>

    </center>

    <a href="{% url 'student:studentdeshboard' %}  "><i class="fas fa-tachometer-alt"></i><span>Dashboard</span></a>
    <a href=" {% url 'student:student_exam' %} "><i class="fas fa-book"></i><span>Exam</span></a>
    <a href=" {% url 'student:student_marks' %}"><i class="fas fa-sort-numeric-up"></i><span>My Marks</span></a>
    
  </div>
  <!--sidebar end-->


  <!--content start-->
  <div class="content">
    <br><br><br><br>
    {% block content %}

    {% endblock content %}


    <br><br><br>
    
  </div>
  <!--content end-->
</body>

</html>

templates/student/check_marks.html
{% extends 'student/base_student.html' %}
{% block content %}
{% load static %}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">My Marks</h6>
    </div>
    <table class="table table-hover table-bordered" id="dev-table">
      <thead>
        <tr>

          <th>Course</th>
          <th>Total Marks</th>
          <th>Number of Attempts</th>
          <th>Exam Date</th>
        </tr>
      </thead>
      {% for t in results %}
      <tr>

        <td> {{t.exam.course_name}}</td>
        <td> {{t.marks}}</td>
        <td>Attempt {{ forloop.counter }}</td>
        <td> {{t.date}}</td>
        
        
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}

templates/student/signin.html
{% extends 'base.html' %}
{% load static  %}
{% block title  %}Student Signin{% endblock title  %}
{% block student_mainblock %}

    <!-- Page Header Start -->
        <div class="page-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2>Sign in </h2>
                    </div>
                    <div class="col-12">
                        <a href=" {% url 'index' %} ">Home</a>
                        <a href="">Sign in</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page Header End -->


        <!-- signin Start -->
        <div class="contact">
            <div class="container">
            		<div class="col-12 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="contact-form">
                            <div id="success"></div>                            
                            <form method="post">
                            {% csrf_token %}
                                <div class="control-group">
                                    <input name="email" type="email" class="form-control" id="email" placeholder="Email-id" required="true" data-validation-required-message="Please Enter your Contact number" />
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="control-group">
                                    <input name="password" type="password" class="form-control" id="password" placeholder="Password" required="true" data-validation-required-message="Please Enter your Contact number" />
                                    <p class="help-block text-danger"></p>
                                </div>                
                                <div class="control-group">
                                    <button class="btn" type="submit" id="registerbtn">Login</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        <!-- sign in End -->
{% endblock student_mainblock  %}
   

templates/student/signup.html
{% extends 'base.html' %}
{% load static  %}
{% block title  %}Student Signup{% endblock title  %}
{% block student_mainblock %}

    <!-- Page Header Start -->
        <div class="page-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2>Sign up</h2>
                    </div>
                    <div class="col-12">
                        <a href=" {% url 'index' %} ">Home</a>
                        <a href="">Sign up</a>
                    </div>
                    <div class="col-12">
                        <p class="help-block text-danger">Already registered?
                        <a href=" {% url 'student:signin' %} ">Sign in</a></p>                   
                    </div>
                </div>
            </div>
        </div>
        <!-- Page Header End -->


        <!-- Signup Start -->
        <div class="contact">
            <div class="container">
                <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
                    <p>if you give the Exam</p>
                    <h2>First you Register...</h2>
                </div>
					<div class="col-12 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="contact-form">
                            <div id="success"></div>
                            <form method="post" enctype="multipart/form-data">

                            {% csrf_token %}
                                <div class="control-group">
                                    <input name="firstname" type="text" class="form-control" id="firstname" placeholder="Firstname" required="true" data-validation-required-message="Please enter your name" />
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="control-group">
                                    <input name="lastname" type="text" class="form-control" id="lastname" placeholder="Lastname" required="true" data-validation-required-message="Please enter your name" />
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="control-group">
                                    <input name="contact" type="Phone" class="form-control" id="contact" placeholder="Contact number" required="true" data-validation-required-message="Please Enter your Contact number" />
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="control-group">
                                    <input name="email" type="email" class="form-control" id="email" placeholder="Email-id" required="true" data-validation-required-message="Please enter your email" />
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="control-group">
                                    <input name="password" type="password" class="form-control" id="password" placeholder="Password" required="true" data-validation-required-message="Please Enter your Contact number" />
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="control-group">
                                    <input name="city" type="text" class="form-control" id="city" placeholder="City" required="true" data-validation-required-message="Please Enter your Contact number" />
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="control-group">
                                    <label for="profile_photo">Profile Photo</label>
                                    <input name="profile_photo" type="file" accept="image/*" id="profile_photo" class="form-control" placeholder=""  required="true">
                                    <p class="help-block text-danger"></p>
                                </div>                
                                <div class="control-group">
                                    <button class="btn" type="submit" id="registerbtn">Register</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        <!-- Contact End -->



{% endblock student_mainblock  %}
   

templates/student/start_exam.html
{% extends 'student/base_student.html' %}
{% block content %}
{% load static%}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>


<div class="jumbotron my-4">

  {% comment %} <form class="form" autocomplete="off" onsubmit="return saveAns()"  action="/student/calculate_marks" method="POST"> {% endcomment %}
  <form class="form" method="POST">
    {% csrf_token %}
    <h2 style="text-align: center;">Course: {{course.course_name}}</h2>
    {% for q in questions%}
    <h3 class="text-danger">{{ forloop.counter }}. {{q.question}}</h3><h4 style="text-align: right;">[{{q.marks}} Marks]</h4>
    
        <input type="hidden" name="csrfmiddlewaretoken" value="{}">
                
          <div class="form-check mx-4">
            <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{q.option1}}" value="{{q.option1}}">
            <label class="form-check-label" for="option1">
              {{q.option1}}
            </label>
          </div>

        
          <div class="form-check mx-4">
            <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{q.option2}}" value="{{q.option2}}">
            <label class="form-check-label" for="option2">
              {{q.option2}}
            </label>
          </div>

        
          <div class="form-check mx-4">
            <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{q.option3}}" value="{{q.option3}}">
            <label class="form-check-label" for="option3">
              {{q.option3}}
            </label>
          </div>        
          
        {% endfor %}
        <input class="btn btn-success btn-lg" style="border-radius: 0%;"  type="submit" value="Submit Answers">  
    </form>
  </div>
<script> 
    {% comment %} function saveAns(){  
        var ele = document.getElementsByTagName('input'); 
        for(i = 0; i < ele.length; i++) { 
            if(ele[i].type="radio") { 
                if(ele[i].checked){        
                  setCookie(ele[i].name,ele[i].value,3)
                }
            } 
        }           
    }    
  function setCookie(cname, cvalue, exdays) {
  var d = new Date();
  d.setTime(d.getTime() + (exdays*24*60*60*1000));
  var expires = "expires="+ d.toUTCString();
  document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
} {% endcomment %}
</script> 
<br><br><br><br><br><br>
{% endblock content %}

templates/student/student_exam.html
{% extends 'student/base_student.html' %}
{% block content %}
{%load static%}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Available Courses</h6>
    </div>
    <table class="table table-hover table-bordered" id="dev-table">
      <thead>
        <tr>

          <th>Exam Name</th>
          
          <th>Action</th>
        </tr>
      </thead>
      {% for t in courses %}
      <tr>

        <td> {{t.course_name}}</td>
        
        <td><a class="btn btn-success btn-sm" style="border-radius:0px;" href="{% url 'student:take_exam' t.id  %}"><span class="glyphicon glyphicon-check"></span> Attend Exam</a></td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}

templates/student/student_marks.html
{% extends 'student/base_student.html' %}
{% block content %}
{% load static %}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">My Marks</h6>
    </div>
    <table class="table table-hover table-bordered" id="dev-table">
      <thead>
        <tr>

          <th>Course</th>
          
          <th>Action</th>
        </tr>
      </thead>
      {% for t in courses %}
      <tr>
        <td> {{t.course_name}}</td>
        
        <td><a class="btn btn-success btn-sm" style="border-radius:0px;" href=" {% url 'student:check_marks' t.id  %} "><span class="glyphicon glyphicon-eye-open"></span> View Marks</a></td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}

templates/student/take_exam.html
{% extends 'student/base_student.html' %}
{% block content %}
{%load static%}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>


</head>
<br><br>
<div class="container my-4">
    <div class="jumbotron">

        <div class="row">

            <div class="card border-info mx-4 my-4">
                <div class="card-body text-default">

                    <h4 class="card-title">Exam Details :</h4>
                    <p class="card-text">
                        </p><ul style="list-style:decimal;">
                            <li>Course : {{course.course_name}}</li>
                            <li>Total Question : {{total_questions}}</li>
                            <li>Total Marks : {{total_marks}}</li>
                        </ul>
                    <p></p>



                    <h4 class="card-title">Rules :</h4>
                    <p class="card-text">
                        </p><ul style="list-style:decimal;">
                            <li>All questions are MCQ (multiple choice question)</li>
                            <li><span class="text-danger">Only one choice is correct among the given.</span></li>
                            <li>Every question carry different marks.</li>
                            <li>Try to answer ASAP.</li>
                            <li>If you PRESS refresh or go back to the previous page, there will be a new question for you and the question you were on will be counted as number of attempts.</li>
                            <li>Questions are presented randomly.</li>
                            <li>You will be able to view marks immediately once after you submit the answer.</li>
                        </ul>
                    <p></p>
                    <a href=" {% url 'student:start_exam' course.id %} " class="btn btn-success" style="border-radius:0px;">Enter Examination</a>
                </div>  
                <div class="card-footer">Best Of Luck, Students!</div>  
            </div>  
        </div>  

    </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}

templates/student/view_result.html
{% extends 'student/base_student.html' %}
{% block content %}
{% load static %}
<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container" style="margin-right:-60px">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">View Marks</h6>
    </div>
    <table class="table table-hover table-bordered" id="dev-table">
      <thead>
        <tr>
          <th>Exam Name</th>          
          <th>Action</th>
        </tr>
      </thead>
      {% for t in courses %}
      <tr>

        <td> {{t.course_name}}</td>
        
        <td><a class="btn btn-success btn-sm" style="border-radius: 0%;" href="{% url 'student:check_marks' t.id  %}"><span class="glyphicon glyphicon-eye-open"></span> View Marks</a></td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}