Exam/urls.py
from django.contrib import admin
from django.urls import path,include
from Exam import views
urlpatterns = [
    path('',views.index,name="index"),
    # path('about',views.about,name="about"),
    # path('purpose',views.purpose,name="purpose"),
    # path('contact',views.contact,name="contact"),
    
    

]

ONLINE_EXAM/urls.py
from django.contrib import admin
from django.urls import path,include
from Student import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('Exam.urls')),
    path('admin/', include('admin.urls')),
    path('student/',include('Student.urls')),
        
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Student/urls.py
from django.urls import path
from Student import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "student"

urlpatterns = [
    path('',views.index,name="index"),
    path('signup',views.signup,name="signup"),
    path('about',views.about,name="about"),
    path('purpose',views.purpose,name="purpose"),
    path('contact',views.contact,name="contact"),    
    path('signin',views.signin,name="signin"),
    path('studentdeshboard',views.studentdeshboard,name="studentdeshboard"),
    path('stud_feedback/',views.feedback,name="stud_feedback"),
    path('student_exam/',views.student_exam,name="student_exam"),
    path('take_exam/<id>',views.take_exam,name="take_exam"),
    path('start_exam/<id>',views.start_exam,name="start_exam"),
    path('student_marks/',views.student_marks,name="student_marks"),
    path('view_result', views.view_result_view,name='view_result'),
    path('check_marks/<int:pk>',views.check_marks,name='check_marks'),
    path('stud_logout/',views.stud_logout,name="stud_logout"),
    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load static  %}
{% block title  %}About{% endblock title  %}
{% block maincontent %}

        <!-- Page Header Start -->
        <div class="page-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2>About Us</h2>
                    </div>
                    <div class="col-12">
                        <a href=" {% url 'index' %} ">Home</a>
                        <a href="">About Us</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page Header End -->


        <!-- About Start -->
        <div class="about wow fadeInUp" data-wow-delay="0.1s">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-5 col-md-6">
                        <div class="about-img">
                            <img src="{% static 'images/online-exam.jpg' %}" alt="Image" width="400" height="300">
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-6">
                        <div class="section-header text-left">
                            <p>Learn About Us</p>
                            <h2>Welcome to eEXAM</h2>
                        </div>
                        <div class="about-text">
                            <p>
                                We need an online examination system to ensure examination continuity amid any present and unforeseen disruptions, such as the one caused by COVID-19. 
                                Traditional education has suffered immensely because of the ongoing pandemic. 
                            </p>
                            <p>
                                The only way universities can sail through such times is to do away with the pen-and-paper mode of examination and adopt an online examination system.
                                This ensures seamless continuity of academic sessions, widening the scope of an online examination system.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- About End -->


 {% endblock maincontent %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>eEXAM | {% block title %}{% endblock title %}</title>
        
        <!-- Favicon -->
        <link href="../../static/images/favicon.ico" rel="icon">
        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700;800&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet"> 
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>
    <body>
        
        <!-- Nav Bar Start -->
        <div class="navbar navbar-expand-lg bg-dark navbar-dark">
            <div class="container-fluid">
                <a href="" class="navbar-brand"><span>e</span>EXAM</a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav ml-auto">
                        <a href="{% url 'index' %} " class="nav-item nav-link active">Home</a>
                        <a href="{% url 'student:about' %}" class="nav-item nav-link">About</a>
                        <a href="{% url 'student:purpose' %}" class="nav-item nav-link">Purpose</a>
						<a href=" {% url 'student:contact' %} " class="nav-item nav-link">Contact</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Login</a>
                            <div class="dropdown-menu">
                                <a href=" {% url 'student:signup' %} " class="dropdown-item">Student</a>
                                <a href="admin/" class="dropdown-item">Admin</a>
                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
        <!-- Nav Bar End -->

        {% block student_mainblock %}{% endblock student_mainblock %}

        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <strong>{{ message }}!</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        {% endif %}

        {% block maincontent %}{% endblock maincontent %}

        <!-- Footer Start -->
        <div class="footer wow fadeIn" data-wow-delay="0.3s">
            <div class="container-fluid">
                <div class="container">
                    <div class="footer-info">
                        <a href=" {% url 'index' %} " class="footer-logo"><span>e</span>EXAM</a>
                        <div class="footer-menu">
                            <p>+012 345 67890</p>
                            <p>info@example.com</p>
                        </div>
                        <div class="footer-social">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-youtube"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
                <div class="container copyright">
                    <div class="row">
                        <div class="col-md-6">
                            <p>&copy; <a href=" {% url 'index' %}"><span>e</span>EXAM 2021</a>, All Right Reserved.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src=" {% static 'lib/easing/easing.min.js' %}"></script>
        <script src=" {% static 'lib/wow/wow.min.js' %}"></script>
        <script src=" {% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
        <script src=" {% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
        <script src=" {% static 'lib/lightbox/js/lightbox.min.js' %}"></script>
        
        <!-- Contact Javascript File -->
        <script src=" {% static 'mail/jqBootstrapValidation.min.js' %}"></script>
        <script src=" {% static 'mail/contact.js' %}"></script>

        <!-- Template Javascript -->
        <script src=" {% static 'js/main.js' %}"></script>
    </body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static  %}
{% block title  %}Contact{% endblock title  %}
{% block maincontent %}
       <!-- Page Header Start -->
        <div class="page-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2>Contact</h2>
                    </div>
                    <div class="col-12">
                        <a href=" {% url 'index' %} ">Home</a>
                        <a href="">Contact</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page Header End -->


        <!-- Contact Start -->
        <div class="contact">
            <div class="container">
                <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
                    <p>Get In Touch</p>
                    <h2>For Any Query</h2>
                </div>
					<div class="col-12 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="contact-form">
                            <div id="success"></div>
                            <form  method="post">

                            {% csrf_token %}
                                <div class="control-group">
                                    <input name="username" type="text" class="form-control" id="name" placeholder="Your Name" required="required" data-validation-required-message="Please enter your name" />
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="control-group">
                                    <input name="email" type="email" class="form-control" id="email" placeholder="Your Email-id" required="required" data-validation-required-message="Please enter your email" />
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="control-group">
                                    <input name="phone" type="Phone" class="form-control" id="contact" placeholder="Contact number" required="required" data-validation-required-message="Please Enter your Contact number" />
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="control-group">
                                    <textarea name="message" class="form-control" id="message" placeholder="Message" required="required" data-validation-required-message="Please enter your message"></textarea>
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div>
                                    <button class="btn" type="submit" id="sendMessageButton">Send Message</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        <!-- Contact End -->
 {% endblock maincontent %}

templates/footer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <!-- Favicon -->
        <link href="../../static/images/favicon.ico" rel="icon">
        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700;800&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet"> 
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <div class="footer wow fadeIn" data-wow-delay="0.3s">
            <div class="container-fluid">
                <div class="container">
                    <div class="footer-info">
                        <a href=" {% url 'index' %} " class="footer-logo"><span>e</span>EXAM</a>
                        <div class="footer-menu">
                            <p>+012 345 67890</p>
                            <p>info@example.com</p>
                        </div>
                        <div class="footer-social">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-youtube"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
                <div class="container copyright">
                    <div class="row">
                        <div class="col-md-6">
                            <p>&copy; <a href=" {% url 'index' %}"><span>e</span>EXAM 2021</a>, All Right Reserved.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src=" {% static 'lib/easing/easing.min.js' %}"></script>
        <script src=" {% static 'lib/wow/wow.min.js' %}"></script>
        <script src=" {% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
        <script src=" {% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
        <script src=" {% static 'lib/lightbox/js/lightbox.min.js' %}"></script>
        
        <!-- Contact Javascript File -->
        <script src=" {% static 'mail/jqBootstrapValidation.min.js' %}"></script>
        <script src=" {% static 'mail/contact.js' %}"></script>

        <!-- Template Javascript -->
        <script src=" {% static 'js/main.js' %}"></script>
    
</html>

templates/index.html
{% extends 'base.html' %}
{% load static  %}
{% block title  %}Home{% endblock title  %}
{% block maincontent %}

        <!-- home1 Start -->
        <div class="hero">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-sm-12 col-md-6">
                    <br><br><br>
                        <div class="hero-text">
                            <h1>eExam</h1>
                            <p>
                                An online examination system is a computer-based test system that can be used to conduct computer based tests online. 
                                This examination system uses fewer resources and reduces the need for question papers and answer scripts, exam room scheduling, arranging invigilators, coordinating with examiners, and more.
                            </p> 
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6 d-none d-md-block left">
                    <br><br><br>
                        <div class="hero-image">
                            <img src="{% static 'images/exam.jpg' %}" alt="exam Image">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- home1 End -->


        <!-- About Start -->
        <div class="about wow fadeInUp" data-wow-delay="0.1s">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-5 col-md-6">
                        <div class="about-img">
                            <img src="{% static 'images/online-exam.jpg' %}" alt="Image" width="400" height="300">
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-6">
                        <div class="section-header text-left">
                            <p>Learn About Us</p>
                            <h2>Welcome to eEXAM</h2>
                        </div>
                        <div class="about-text">
                            <p>
                                We need an online examination system to ensure examination continuity amid any present and unforeseen disruptions, such as the one caused by COVID-19. 
                                Traditional education has suffered immensely because of the ongoing pandemic. 
                            </p>
                            <p>
                                The only way universities can sail through such times is to do away with the pen-and-paper mode of examination and adopt an online examination system.
                                This ensures seamless continuity of academic sessions, widening the scope of an online examination system.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- About End -->
      
        <!-- purpose Start -->
        <div class="discount wow zoomIn" data-wow-delay="0.1s">
            <div class="container">
                <div class="section-header text-center">
                    <h2><span>Purpose</span></h2>
                </div>
                <div class="container discount-text">
                    <p>
                        The purpose of the online examination system is to test the subject knowledge of the students. 
                        Such a system eliminates logistical hassles and drawbacks in the traditional mode of the pen-and-paper examination.
                        An online exam is a great way of conducting tests and other important exams with help of the internet. 
                        An online exam needs a device capable of accessing the internet such as a computer or a smartphone.
                        This can be either done at an examination center or at home.
                    </p>
                </div>
            </div>
        </div>
        <!-- purpose End -->

{% endblock maincontent %} 

templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>eEXAM | {% block title %}{% endblock title %}</title>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Free Website Template" name="keywords">
        <meta content="Free Website Template" name="description">

        <!-- Favicon -->
        <link href="../../static/images/favicon.ico" rel="icon">
        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700;800&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet"> 
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>


    <body>
        
        <!-- Nav Bar Start -->
        <div class="navbar navbar-expand-lg bg-dark navbar-dark">
            <div class="container-fluid">
                <a href="index.html" class="navbar-brand"><span>e</span>EXAM</a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav ml-auto">
                        <a href="{% url 'index' %} " class="nav-item nav-link active">Home</a>
                        <a href="{% url 'about' %}" class="nav-item nav-link">About</a>
                        <a href="{% url 'purpose' %}" class="nav-item nav-link">Purpose</a>
						<a href=" {% url 'contact' %} " class="nav-item nav-link">Contact</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Login</a>
                            <div class="dropdown-menu">
                                <a href="#" class="dropdown-item">Student</a>
                                <a href="admin/" class="dropdown-item">Admin</a>
                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
        <!-- Nav Bar End -->

        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src=" {% static 'lib/easing/easing.min.js' %}"></script>
        <script src=" {% static 'lib/wow/wow.min.js' %}"></script>
        <script src=" {% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
        <script src=" {% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
        <script src=" {% static 'lib/lightbox/js/lightbox.min.js' %}"></script>
        
        <!-- Contact Javascript File -->
        <script src=" {% static 'mail/jqBootstrapValidation.min.js' %}"></script>
        <script src=" {% static 'mail/contact.js' %}"></script>

        <!-- Template Javascript -->
        <script src=" {% static 'js/main.js' %}"></script>
    </body>
</html>

templates/purpose.html
{% extends 'base.html' %}
{% load static  %}
{% block title  %}Purpose{% endblock title  %}
{% block maincontent %}

        <!-- Page Header Start -->
        <div class="page-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2>Purpose</h2>
                    </div>
                    <div class="col-12">
                        <a href=" {% url 'index' %} ">Home</a>
                        <a href="">Purpose</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page Header End -->


<!-- purpose Start -->
        <div class="discount wow zoomIn" data-wow-delay="0.1s">
            <div class="container">
                <div class="section-header text-center">
                    <h2><span>Purpose</span></h2>
                </div>
                <div class="container discount-text">
                    <p>
                        The purpose of the online examination system is to test the subject knowledge of the students. 
                        Such a system eliminates logistical hassles and drawbacks in the traditional mode of the pen-and-paper examination.
                        An online exam is a great way of conducting tests and other important exams with help of the internet. 
                        An online exam needs a device capable of accessing the internet such as a computer or a smartphone.
                        This can be either done at an examination center or at home.
                    </p>
                </div>
            </div>
        </div>
<!-- purpose End -->
 {% endblock maincontent %}